### ISSUE TITLE
Import fails after freshly cloned repository -> White squares: preview22

### ISSUE THREAD

**Issue by jganser** [Unity-Technologies/vector-graphics-samples#14] opened 2018-11-29 08:05 UTC
At our company we use a gitlab CI Runner to build our solutions, sadly when ever one does a clean clone of  the repository, all svgs are not imported correctly. One has to make a reimport and change the generated asset type to textured sprite, for it to work in the UI, again.

On our developer machines that's not the big issue, but on the CI it's a real issue. Since the steps I mentioned above are manual steps. Didn't find a solution for automisation on reimporting folders and changing that field, while also applying the changes, to it.

I guess it's some issue with reimporting the svgs.

**Comment by mcoted** [comment] 2018-11-29 14:46
@jganser I tried a fresh clone and the SVG assets were properly imported.  Can you tell me more about the exact steps you take to reproduce the issue?  Also, tell me more about your environment (OS + Unity version).

After a clean clone of the project, every SVG should import properly.  However, I suspect there may be issues that require a reimport of the SVG files if you reopen the same project with a different version of Unity.

**Comment by jganser** [comment] 2019-01-10 10:50
Sry, for  the late notice. Hope you had good holiday. Here are some more specifics:

We are using Unity version 2018.3 (latest release)
Only Windows10 as OS on all machines.

Latest status is that the files including meta files get pushed into the repository and cloned by the CI Runner. Than the CI Runner starts the headless build process, via command line unity script call. In that process the svg were seen as type vectorgrapahics and not as textured sprite, like the meta data described them.
Our workaround is that we forcefully reimport the svgs and set their type to textured sprite manually from the code side before the build starts.

**Comment by ManuelRauber** [comment] 2019-07-01 06:57
@mcoted I've the same problem as described by @jganser 

The problem also exists in Unity Cloud Build, which makes it currently unusable for me, since the generated executables contain all white squares. 

Unity: 2019.1.8f1
Package: preview27
macOS latest

The workaround described by @jganser works for me as well, at least on the Unity installed on my machine, since I can not do that on Cloud Build :-) 

And it's only the case after a fresh cloned repo or after a `git clean -xdf` (which basically removes all ignored stuff and resets everything, so its basically freshly cloned).

Here is a video with the problem in the editor: https://www.youtube.com/watch?v=gyldCB3CLFM

Interesting behavior when I recorded the video, which was not the case in any trying before: Some of the image have been imported correctly, some not, even being the same import settings. Maybe it's according to the SVG images? If you want, I can give you (@mcoted) access to the Game's repository, so you can try it out yourself, or at least give you all the SVG's I'm importing.

**Comment by mcoted** [comment] 2019-07-01 12:00
@ManuelRauber This is odd, I was sure this was fixed with the 2018.3.9 release that introduced this bugfix: "Fixed SVG sprites are constantly re-imported when added into prefabs. (1125015)"

I'll try to reproduce this week and I'll get back to you if I need more info.  Thanks!

**Comment by ManuelRauber** [comment] 2019-07-01 12:02
@mcoted Thanks for your fast response! I'm happy to help to get this issue fixed. 

(btw. as I've seen this in #3: would be nice if you consider open-sourcing the package, as done with other Unity packages (e.g. new input system. SVG graphics are super neat for 2D development, and people would be happy to contribute) :-)

**Comment by mcoted** [comment] 2019-07-05 19:22
The issue is that one of our shaders fails to load when doing a fresh AssetDatabase import (with a clean Library folder).  We'll work on a fix that should hopefully be available in the next VectorGraphics package release.

**Comment by mcoted** [comment] 2019-07-10 13:00
Should be fixed with 1.0.0-preview.28

**Closed by mcoted** 2019-07-10 13:00 UTC
